apiVersion: v1
kind: Pod
metadata:
  name: my-app1
  labels:
    type: frontend
spec:
  containers:
    - name: simple-webapp-color
      image: subodhdere/webapp-color
      envFrom:
      - configMapRef:
          name: cmenv
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: mycolor
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app1
  labels:
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: test
        mountPath: "/config"
  volumes:
  - name: test
    configMap:
      name: cmenv
