apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: days-app-ingress
  namespace: sample
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: minikube-example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix  
            backend:
              service:
                name: static-web-service-v1
                port:
                  number: 80
          - path: /v2
            pathType: Prefix  
            backend:
              service:
                name: static-web-service-v2
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service-v1
  namespace: sample
spec:
  ports:
    - port: 80
  selector:
    app: v1
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service-v2
  namespace: sample
spec:
  ports:
    - port: 80
  selector:
    app: v2
---
apiVersion: v1                          
kind: Pod                               
metadata:  
  namespace: sample                             
  name: p1
  labels:
    app: v1                              
spec:                                   
  containers:                           
  - image: subodhdere/k8sdemo:v1
    name: c1
---
apiVersion: v1                          
kind: Pod                               
metadata:  
  namespace: sample                             
  name: p2
  labels:
    app: v2                              
spec:                                   
  containers:                           
  - image: subodhdere/k8sdemo:v2
    name: c2
