apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    type: frontend
spec:
  containers:
    - name: simple-webapp-color
      image: kodekloud/webapp-color
      env:
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
              name: clsecret
              key: clr
              
---

apiVersion: v1
data:
  ssubodh: ZGVyZQ==
#immutable: true    => secrets cant be edited if we enable this setting
kind: Secret
metadata:
  name: s1
  namespace: default
type: Opaque
